name: larrak-dev
channels:
  - conda-forge
  - defaults
dependencies:
  # Include all base environment dependencies
  - python>=3.9,<3.12
  
  # Core optimization dependencies
  - casadi>=3.6.0
  - ipopt>=3.14.0
  
  # Numerical computing
  - numpy>=1.24.0
  - scipy>=1.10.0
  - scikit-learn>=1.1.0
  - joblib>=1.0
  
  # Visualization
  - matplotlib>=3.7.0
  
  # Development tools
  - pytest>=7.4.0
  - pytest-cov>=4.1.0
  - mypy>=1.5.0
  - ruff>=0.0.280
  - hypothesis>=6.82.0
  
  # Additional development tools
  - jupyter
  - ipython
  - notebook
  - jupyterlab
  
  # Code quality and development
  - pre-commit
  - black  # Alternative formatter (optional)
  - isort  # Import sorting
  
  # Documentation
  - sphinx
  - sphinx-rtd-theme
  - myst-parser
  
  # Testing and debugging
  - pytest-xdist  # Parallel testing
  - pytest-mock
  - coverage
  
  # Interactive development
  - ipdb  # Enhanced debugger
  - rich  # Rich terminal output
  
  # Package management
  - pip
  - conda-build
  - conda-verify
  
  # Utilities
  - colorama
  - tqdm
  - click  # CLI framework
  
  # Pip packages for development
  - pip:
    # Add any pip-only development packages here
    # - some-dev-package>=1.0.0
