# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import warnings

import grpc

try:
    from . import cem_pb2 as cem__pb2
except ImportError:
    import cem_pb2 as cem__pb2

GRPC_GENERATED_VERSION = "1.76.0"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + " but the generated code in cem_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class CEMServiceStub(object):
    """============================================================
    Service Definition
    ============================================================

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetVersion = channel.unary_unary(
            "/larrak.cem.CEMService/GetVersion",
            request_serializer=cem__pb2.VersionRequest.SerializeToString,
            response_deserializer=cem__pb2.VersionInfo.FromString,
            _registered_method=True,
        )
        self.HealthCheck = channel.unary_unary(
            "/larrak.cem.CEMService/HealthCheck",
            request_serializer=cem__pb2.HealthCheckRequest.SerializeToString,
            response_deserializer=cem__pb2.HealthCheckResponse.FromString,
            _registered_method=True,
        )
        self.ValidateMotion = channel.unary_unary(
            "/larrak.cem.CEMService/ValidateMotion",
            request_serializer=cem__pb2.MotionValidationRequest.SerializeToString,
            response_deserializer=cem__pb2.MotionValidationResponse.FromString,
            _registered_method=True,
        )
        self.GetThermoEnvelope = channel.unary_unary(
            "/larrak.cem.CEMService/GetThermoEnvelope",
            request_serializer=cem__pb2.ThermoEnvelopeRequest.SerializeToString,
            response_deserializer=cem__pb2.ThermoEnvelopeResponse.FromString,
            _registered_method=True,
        )
        self.GetGearInitialGuess = channel.unary_unary(
            "/larrak.cem.CEMService/GetGearInitialGuess",
            request_serializer=cem__pb2.GearInitialGuessRequest.SerializeToString,
            response_deserializer=cem__pb2.GearInitialGuessResponse.FromString,
            _registered_method=True,
        )
        self.EvaluateCandidates = channel.unary_unary(
            "/larrak.cem.CEMService/EvaluateCandidates",
            request_serializer=cem__pb2.EvaluationRequest.SerializeToString,
            response_deserializer=cem__pb2.EvaluationResponse.FromString,
            _registered_method=True,
        )


class CEMServiceServicer(object):
    """============================================================
    Service Definition
    ============================================================

    """

    def GetVersion(self, request, context):
        """Health and version"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def HealthCheck(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ValidateMotion(self, request, context):
        """Motion validation (pre-Phase 3)"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetThermoEnvelope(self, request, context):
        """Thermodynamic envelope (pre-Phase 1)"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetGearInitialGuess(self, request, context):
        """Gear initialization"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def EvaluateCandidates(self, request, context):
        """Batch evaluation (for dashboards)"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_CEMServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "GetVersion": grpc.unary_unary_rpc_method_handler(
            servicer.GetVersion,
            request_deserializer=cem__pb2.VersionRequest.FromString,
            response_serializer=cem__pb2.VersionInfo.SerializeToString,
        ),
        "HealthCheck": grpc.unary_unary_rpc_method_handler(
            servicer.HealthCheck,
            request_deserializer=cem__pb2.HealthCheckRequest.FromString,
            response_serializer=cem__pb2.HealthCheckResponse.SerializeToString,
        ),
        "ValidateMotion": grpc.unary_unary_rpc_method_handler(
            servicer.ValidateMotion,
            request_deserializer=cem__pb2.MotionValidationRequest.FromString,
            response_serializer=cem__pb2.MotionValidationResponse.SerializeToString,
        ),
        "GetThermoEnvelope": grpc.unary_unary_rpc_method_handler(
            servicer.GetThermoEnvelope,
            request_deserializer=cem__pb2.ThermoEnvelopeRequest.FromString,
            response_serializer=cem__pb2.ThermoEnvelopeResponse.SerializeToString,
        ),
        "GetGearInitialGuess": grpc.unary_unary_rpc_method_handler(
            servicer.GetGearInitialGuess,
            request_deserializer=cem__pb2.GearInitialGuessRequest.FromString,
            response_serializer=cem__pb2.GearInitialGuessResponse.SerializeToString,
        ),
        "EvaluateCandidates": grpc.unary_unary_rpc_method_handler(
            servicer.EvaluateCandidates,
            request_deserializer=cem__pb2.EvaluationRequest.FromString,
            response_serializer=cem__pb2.EvaluationResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "larrak.cem.CEMService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers("larrak.cem.CEMService", rpc_method_handlers)


# This class is part of an EXPERIMENTAL API.
class CEMService(object):
    """============================================================
    Service Definition
    ============================================================

    """

    @staticmethod
    def GetVersion(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/larrak.cem.CEMService/GetVersion",
            cem__pb2.VersionRequest.SerializeToString,
            cem__pb2.VersionInfo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def HealthCheck(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/larrak.cem.CEMService/HealthCheck",
            cem__pb2.HealthCheckRequest.SerializeToString,
            cem__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def ValidateMotion(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/larrak.cem.CEMService/ValidateMotion",
            cem__pb2.MotionValidationRequest.SerializeToString,
            cem__pb2.MotionValidationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetThermoEnvelope(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/larrak.cem.CEMService/GetThermoEnvelope",
            cem__pb2.ThermoEnvelopeRequest.SerializeToString,
            cem__pb2.ThermoEnvelopeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetGearInitialGuess(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/larrak.cem.CEMService/GetGearInitialGuess",
            cem__pb2.GearInitialGuessRequest.SerializeToString,
            cem__pb2.GearInitialGuessResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def EvaluateCandidates(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/larrak.cem.CEMService/EvaluateCandidates",
            cem__pb2.EvaluationRequest.SerializeToString,
            cem__pb2.EvaluationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
