services:
  redis:
    image: redis:7-alpine
    container_name: larrak-redis
    networks:
      - larrak-internal
    volumes:
      - redis_data:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 3

  weaviate:
    command:
      - --host
      - 0.0.0.0
      - --port
      - "8080"
      - --scheme
      - http
    image: semitechnologies/weaviate:1.27.0
    # ports:
    #   - "8080:8080"
    #   - "50052:50051"
    volumes:
      - weaviate_data:/var/lib/weaviate
    restart: on-failure:0
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: "true"
      PERSISTENCE_DATA_PATH: "/var/lib/weaviate"
      DEFAULT_VECTORIZER_MODULE: "none"
      CLUSTER_HOSTNAME: "node1"
    networks:
      - larrak-internal
    logging:
      driver: "local"
      options:
        max-size: "50m"
        max-file: "2"

volumes:
  weaviate_data:
  redis_data:

networks:
  larrak-internal:
    driver: bridge
