import weaviate
import weaviate.classes.config as wvc

def create_schema(client: weaviate.WeaviateClient):
    # 1. Module (Static Definition)
    if not client.collections.exists("Module"):
        client.collections.create(
            name="Module",
            description="A declared processing module or script",
            properties=[
                wvc.Property(name="module_id", data_type=wvc.DataType.TEXT, skip_vectorization=True),
                wvc.Property(name="entrypoint", data_type=wvc.DataType.TEXT, skip_vectorization=True),
                wvc.Property(name="description", data_type=wvc.DataType.TEXT),  # Vectorized for semantic search
                wvc.Property(name="owner", data_type=wvc.DataType.TEXT),
            ],
            vectorizer_config=wvc.Configure.Vectorizer.text2vec_transformers()
        )

    # 2. Run (Execution Instance)
    if not client.collections.exists("Run"):
        client.collections.create(
            name="Run",
            description="An execution instance of a module",
            properties=[
                wvc.Property(name="run_id", data_type=wvc.DataType.TEXT, skip_vectorization=True),
                wvc.Property(name="start_time", data_type=wvc.DataType.DATE),
                wvc.Property(name="end_time", data_type=wvc.DataType.DATE),
                wvc.Property(name="status", data_type=wvc.DataType.TEXT, skip_vectorization=True),
                wvc.Property(name="args", data_type=wvc.DataType.TEXT_ARRAY, skip_vectorization=True),
                wvc.Property(name="env", data_type=wvc.DataType.TEXT, skip_vectorization=True), # JSON blob
                wvc.Property(name="tags", data_type=wvc.DataType.TEXT_ARRAY),
                wvc.Property(name="logs", data_type=wvc.DataType.TEXT, skip_vectorization=True), # High volume logs
            ],
            references=[
                wvc.ReferenceProperty(name="executed_module", target_collection="Module"),
                wvc.ReferenceProperty(name="generated_artifacts", target_collection="Artifact"),
                wvc.ReferenceProperty(name="used_input_artifacts", target_collection="Artifact"),
            ],
             # Runs usually don't need semantic search on their metadata, but tags might be useful.
             # vectorizer_config=wvc.Configure.Vectorizer.none() 
             # Keeping default vectorizer to allow searching by tags/notes if we add them.
        )

    # 3. Artifact (Data Object)
    if not client.collections.exists("Artifact"):
        client.collections.create(
            name="Artifact",
            description="A file or dataset generated by a run",
            properties=[
                wvc.Property(name="artifact_id", data_type=wvc.DataType.TEXT, skip_vectorization=True),
                wvc.Property(name="path", data_type=wvc.DataType.TEXT, skip_vectorization=True),
                wvc.Property(name="role", data_type=wvc.DataType.TEXT), # input, output, report
                wvc.Property(name="content_hash", data_type=wvc.DataType.TEXT, skip_vectorization=True),
                wvc.Property(name="meta", data_type=wvc.DataType.TEXT), # JSON blob
                wvc.Property(name="summary", data_type=wvc.DataType.TEXT), # Vectorized description of content
            ],
             references=[
                wvc.ReferenceProperty(name="generated_by", target_collection="Run"),
            ],
            vectorizer_config=wvc.Configure.Vectorizer.text2vec_transformers(
                vectorize_class_name=False
            )
        )

    # 4. CodeSymbol (Function/Class - for semantic linking)
    if not client.collections.exists("CodeSymbol"):
        client.collections.create(
            name="CodeSymbol",
            description="A function, class, or file in the codebase",
            properties=[
                wvc.Property(name="name", data_type=wvc.DataType.TEXT),
                wvc.Property(name="path", data_type=wvc.DataType.TEXT, skip_vectorization=True),
                wvc.Property(name="type", data_type=wvc.DataType.TEXT), # function, class
                wvc.Property(name="content", data_type=wvc.DataType.TEXT), # The actual code signature/docstring
            ],
             references=[
                wvc.ReferenceProperty(name="implemented_in", target_collection="Module"),
            ],
        )

    # 5. Tracker (Requirement/Task)
    if not client.collections.exists("Tracker"):
        client.collections.create(
            name="Tracker",
            description="A requirement, task, or decision note",
            properties=[
                wvc.Property(name="tracker_id", data_type=wvc.DataType.TEXT, skip_vectorization=True),
                wvc.Property(name="title", data_type=wvc.DataType.TEXT),
                wvc.Property(name="body", data_type=wvc.DataType.TEXT),
                wvc.Property(name="kind", data_type=wvc.DataType.TEXT), # bug, feature, decision
            ],
            references=[
                 wvc.ReferenceProperty(name="related_code", target_collection="CodeSymbol"),
                 wvc.ReferenceProperty(name="related_artifacts", target_collection="Artifact"),
            ]
        )
